steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        access_token=$(gcloud auth print-access-token)
        echo "El token de acceso es: $access_token"
  - name: 'maven:3-jdk-11'
    dir: 'Mock-v1'
    args:
      - mvn
      - install
      - '-Ptest'
      - '-Dorg=$_ORG_NAME'
      - '-Denv=$_ENV_NAME'
      - '-Dfile=$$SERVICE_ACCOUNT_FILE'
    secretEnv: ['SERVICE_ACCOUNT_FILE']
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
    secretManager:
      - versionName: projects/255657685440/secrets/service-account-apigee-key/versions/1
        env: 'SERVICE_ACCOUNT_FILE'
