steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud auth application-default print-access-token > token.txt' ]
  dir: 'Mock-v1'
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', 'mvn install -Ptest -Dorg=${_ORG_NAME} -Denv=${_ENV_NAME} -Dbearer=$(cat token.txt)']
  dir: 'Mock-v1'
options:
  logging: CLOUD_LOGGING_ONLY
