steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        access_token=$(gcloud auth print-access-token)
        echo "El token de acceso es: $access_token"
  - name: 'maven:3-jdk-11'
    dir: 'Mock-v1'
    args:
      - mvn
      - install
      - '-Ptest'
      - '-Dorg=$_ORG_NAME'
      - '-Denv=$_ENV_NAME'
      - '-Dbearer=ya29.c.b0Aaekm1IyCeYUVKh5amZr0QuiVmfqtFp4NABpCWE99-6cTwLhvY3FIatFRs6QzM0010B2uZwCy5cwYU06JSQf_Wm33PtOhUB2TAmlucQ8bZs-CMFDlwhXlKglmJwUdJ3nWw3A0ZruRu-IUT9kBXFGPA2wWkYnnxjE8IDAqwAfGB88HHNxSJFjaAlCaDPF4hLuuRmdW0jd0ZlLNmNIjF4TE-dz6im43j3tXo2_BaOhmv_YUm-pOY6E5rNzWW030Z02xU5OZIcSco0s9gH279K9FktswVfMx2OoYkwbFYdsojIdmxJSUagOd4kaI1Q8StdbW_IzsBtpeQnyZSkbvwen5RvJwXwdzQbWw6Iw3QRpfMqVz1iWbqIvJqYuRixknZi711edlRor-XvRjuOJX7gsovS5brYJ86vxjf8O9byow8ednosiJwMRxtlyrZB9fSR71Ujty9speZo_cFS4isschQpy_iWigzp7gbV_WkJY1YvvWv-s9Zf__z2xZ6fMOoqY1zha9ubosW-ilsRMsy_XbiinJa01eI8euFfbVhQhiVlmn0ZUgsVcx0chUmrgUk2xenkOW6RUf3-QfeI7jtd1F2Y-l4zXSip8ae7X6h6usWl9ZjVMdjuOwbkQM0g92RbsS4hz7QRctXaxW342Qwp-V4jsciruwqh62UfQpI70tfdiac0g_zaqqzviFxOtbZBtcwz1V95l1e8q_0B9RBS5X9cdrkR77SvWU0VJcU9biyoXjvXkjJfnnFdbk4Znn0yyhJthvztf5Jw90svlYhU5x33bYQBQ7kZvZg60WFzXaaJMw-v9IVw-r-4MFpv-giuX8_9dqlxybMFzdy8fI9UzQMqRfFdFdkfss1x58tXlZVXs-U2aRyfc4UJjbZYzvybw21t3cV_MWpJ22qqjXYd_IZI4szj3UpY7y_-r_mVrXw4Zfy2xJqspb5vfts4OVsVvjQZahW-ziqf6qi_XInO_qjuXOOrJaVcBsg--7IhzYM2ol6kF5jRug1i'
options:
  logging: CLOUD_LOGGING_ONLY
