steps:
  - name: 'maven:3-jdk-11'
    dir: 'Mock-v1'
    args:
      - mvn
      - install
      - Ptest
      - '-Dorg=$_ORG_NAME'
      - '-Denv=$_ENV_NAME'
      - '-Dbearer=$(gcloud auth print-access-token)'
options:
  logging: CLOUD_LOGGING_ONLY
