steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        _ACCESS_TOKEN=$(gcloud auth print-access-token)
        echo "$_ACCESS_TOKEN" > /workspace/access_token.txt
  - name:  'gcr.io/cloud-builders/mvn'
    entrypoint: 'bash'
    dir: 'Mock-v1'
    args:
      ['mvn', 'install', '-Ptest', '-Dorg=$_ORG_NAME', '-Denv=$_ENV_NAME', '-Dbearer=$(cat /workspace/access_token.txt)']
options:
  logging: CLOUD_LOGGING_ONLY
