steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        _ACCESS_TOKEN=$(gcloud auth print-access-token)
        echo "El token de acceso es: $access_token"
  - name: 'maven:3-jdk-11'
    dir: 'Mock-v1'
    args:
      - mvn
      - install
      - '-Ptest'
      - '-Dorg=$_ORG_NAME'
      - '-Denv=$_ENV_NAME'
      - '-Dbearer=$_ACCESS_TOKEN'
options:
  logging: CLOUD_LOGGING_ONLY
